import  './globals.css';
import { Inter, Manrope } from 'next/font/google';
import { cx } from './utils';
import Header from './Components/Header';

const inter = Inter({ subsets: ['latin'],  display: "swap", variable: "--font-inter"  })
const manrope = Manrope({ subsets: ['latin'],  display: "swap", variable: "--font-manrope" })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      className = {cx(
        inter.variable,
        manrope.variable,
         "font-manrope bg-light "
        )}
        >
          <Header/>
        {children}
        </body>
    </html>
  )
}
