backend:
  name: git-gateway
  branch: main # Your repository branch
media_folder: public/images
public_folder: /images

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { name: title, label: Title, widget: string }
      - { name: date, label: Date, widget: datetime }
      - { name: description, label: Description, widget: text }
      - { name: author, label: Author, widget: string }
      - { name: tags, label: Tags, widget: list }
      - { name: image, label: Featured Image, widget: image }
      - { name: isPublished, label: Published, widget: boolean, default: true }
      - { name: body, label: Body, widget: markdown }
